name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install pytest pytest-cov coverage
          pip install -r requirements.txt || true

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          coverage run -m pytest
          coverage report --fail-under=100
